// Renderiza o DANFSe em Node (mesmo layout de src/lib/nfe/danfse.ts) p/ inspeção.
import { jsPDF } from "jspdf";
import { DOMParser } from "@xmldom/xmldom";
import { readFileSync, writeFileSync } from "node:fs";
const SCR = "/private/tmp/claude-501/-Users-rodrigobelluco-Documents-Claude-CRM-Loja-do-Flu/6c289316-9c38-4d0a-8552-3c797ca128d0/scratchpad";
const idx = process.argv[2] ?? "0";
const xml = readFileSync(`${SCR}/nfse-${idx}.xml`, "utf8");

const el = (r, t) => r.getElementsByTagName(t)[0] ?? null;
const txt = (r, t) => (r ? el(r, t)?.textContent?.trim() ?? "" : "");
const moeda = (v) => { const n = Number(v ?? 0); return Number.isFinite(n) ? n.toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : "0,00"; };
const cnpjMask = (d) => { const s = (d || "").replace(/\D/g, ""); if (s.length === 14) return s.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/, "$1.$2.$3/$4-$5"); return d; };
const cep = (d) => { const s = (d || "").replace(/\D/g, ""); return s.length === 8 ? s.replace(/^(\d{5})(\d{3})$/, "$1-$2") : d; };
const dataBR = (iso) => { if (!iso) return ""; const so = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso); return so ? `${so[3]}/${so[2]}/${so[1]}` : iso; };
const horaBR = (iso) => { if (!iso) return ""; const d = new Date(iso); return isNaN(d.getTime()) ? "" : d.toLocaleTimeString("pt-BR", { timeZone: "America/Sao_Paulo", hour: "2-digit", minute: "2-digit" }); };

const dom = new DOMParser().parseFromString(xml, "application/xml");
const idMatch = xml.match(/Id="NFS(\d{40,60})"/);
const chave = idMatch ? idMatch[1] : txt(dom, "chNFSe");
const emit = el(dom, "emit");
const enderEmit = el(emit ?? dom, "enderNac");
const toma = el(dom, "toma");
const enderToma = el(toma ?? dom, "end");
const valores = el(dom, "valores");

const doc = new jsPDF({ unit: "mm", format: "a4" });
const M = 6, R = 210 - M, Wt = R - M;
const rect = (x, y, w, h) => { doc.setLineWidth(0.2); doc.rect(x, y, w, h); };
const cap = (x, y, t) => { doc.setFont("helvetica", "normal").setFontSize(5); doc.text(t, x + 1, y + 2.4); };
const val = (x, y, w, t, size = 8, bold = false, align = "left") => { doc.setFont("helvetica", bold ? "bold" : "normal").setFontSize(size); const px = align === "right" ? x + w - 1 : align === "center" ? x + w / 2 : x + 1; doc.text(t ?? "", px, y, { align, maxWidth: w - 2 }); };
const field = (x, y, w, h, label, value, opts = {}) => { rect(x, y, w, h); cap(x, y, label); val(x, y + h - 1.6, w, value, opts.size ?? 8, opts.bold, opts.align ?? "left"); };

let y = M;
const hcab = 26, emitW = 96, midW = 46, chaveW = Wt - emitW - midW;
rect(M, y, emitW, hcab);
doc.setFont("helvetica", "bold").setFontSize(8.5);
doc.text(txt(emit, "xNome"), M + 2, y + 4.5, { maxWidth: emitW - 4 });
doc.setFont("helvetica", "normal").setFontSize(6);
doc.text(`CNPJ: ${cnpjMask(txt(emit, "CNPJ"))}`, M + 2, y + 9);
doc.text(`${txt(enderEmit, "xLgr")}, ${txt(enderEmit, "nro")} - ${txt(enderEmit, "xBairro")}`, M + 2, y + 12.5, { maxWidth: emitW - 4 });
doc.text(`${txt(dom, "xLocEmi")}/${txt(enderEmit, "UF")}  CEP: ${cep(txt(enderEmit, "CEP"))}`, M + 2, y + 16);
doc.text(`Fone: ${txt(emit, "fone")}  ${txt(emit, "email")}`, M + 2, y + 19.5, { maxWidth: emitW - 4 });
doc.setFont("helvetica", "bold").setFontSize(6);
doc.text("PRESTADOR DO SERVIÇO", M + 2, y + 23.5);
const mx = M + emitW;
rect(mx, y, midW, hcab);
doc.setFont("helvetica", "bold").setFontSize(9.5);
doc.text("DANFSe", mx + midW / 2, y + 4.5, { align: "center" });
doc.setFont("helvetica", "normal").setFontSize(4.4);
doc.text("Documento Auxiliar da NFS-e", mx + midW / 2, y + 7.5, { align: "center" });
doc.setFontSize(6);
doc.text(`Número: ${txt(dom, "nNFSe")}`, mx + 2, y + 11.5);
doc.text(`Competência: ${dataBR(txt(dom, "dCompet"))}`, mx + 2, y + 14.5);
doc.text(`Emissão: ${dataBR(txt(dom, "dhProc") || txt(dom, "dhEmi"))} ${horaBR(txt(dom, "dhProc"))}`, mx + 2, y + 17.5);
doc.text(`Situação: ${txt(dom, "cStat") === "100" || txt(dom, "cStat") === "107" ? "Autorizada" : txt(dom, "cStat")}`, mx + 2, y + 20.5);
doc.text(`Município: ${txt(dom, "xLocPrestacao")}`, mx + 2, y + 23.5, { maxWidth: midW - 4 });
const cx = mx + midW;
rect(cx, y, chaveW, hcab);
cap(cx, y, "CHAVE DE ACESSO DA NFS-e");
doc.setFont("courier", "bold").setFontSize(7.5);
doc.text((chave || "").replace(/(\d{4})/g, "$1 ").trim(), cx + chaveW / 2, y + 9, { align: "center", maxWidth: chaveW - 3 });
doc.setFont("helvetica", "normal").setFontSize(5);
doc.text("Consulte a autenticidade em nfse.gov.br", cx + chaveW / 2, y + 15, { align: "center" });
doc.text("(informe a chave de acesso acima)", cx + chaveW / 2, y + 18, { align: "center" });
y += hcab;
doc.setFont("helvetica", "bold").setFontSize(6); doc.text("TOMADOR DO SERVIÇO", M, y + 3); y += 4;
field(M, y, Wt * 0.58, 7, "NOME / RAZÃO SOCIAL", txt(toma, "xNome"), { size: 7.5 });
field(M + Wt * 0.58, y, Wt * 0.42, 7, "CNPJ / CPF", cnpjMask(txt(toma, "CNPJ") || txt(toma, "CPF")), { size: 7.5 }); y += 7;
field(M, y, Wt, 7, "ENDEREÇO", `${txt(enderToma, "xLgr")}, ${txt(enderToma, "nro")}${txt(enderToma, "xCpl") ? " - " + txt(enderToma, "xCpl") : ""} - ${txt(enderToma, "xBairro")}  CEP: ${cep(txt(el(enderToma ?? dom, "endNac") ?? enderToma ?? dom, "CEP"))}`, { size: 7 }); y += 7;
doc.setFont("helvetica", "bold").setFontSize(6); doc.text("SERVIÇO PRESTADO", M, y + 3); y += 4;
field(M, y, Wt * 0.5, 7, "TRIBUTAÇÃO NACIONAL", txt(dom, "xTribNac"), { size: 6.5 });
field(M + Wt * 0.5, y, Wt * 0.3, 7, "CÓD. TRIB. NACIONAL", txt(dom, "cTribNac"), { size: 6.5 });
field(M + Wt * 0.8, y, Wt * 0.2, 7, "MUNICÍPIO", txt(dom, "xLocPrestacao"), { size: 6.5 }); y += 7;
rect(M, y, Wt, 26); cap(M, y, "DISCRIMINAÇÃO DOS SERVIÇOS");
doc.setFont("helvetica", "normal").setFontSize(7);
doc.text(doc.splitTextToSize(txt(dom, "xDescServ"), Wt - 4), M + 1.5, y + 5.5); y += 26;
doc.setFont("helvetica", "bold").setFontSize(6); doc.text("VALORES", M, y + 3); y += 4;
const c5 = Wt / 5;
field(M, y, c5, 8, "VALOR DO SERVIÇO", `R$ ${moeda(txt(dom, "vServ"))}`, { size: 7, align: "right" });
field(M + c5, y, c5, 8, "BASE DE CÁLCULO", `R$ ${moeda(txt(valores, "vBC"))}`, { size: 7, align: "right" });
field(M + 2 * c5, y, c5, 8, "ALÍQUOTA ISSQN", `${moeda(txt(valores, "pAliqAplic"))}%`, { size: 7, align: "right" });
field(M + 3 * c5, y, c5, 8, "VALOR ISSQN", `R$ ${moeda(txt(valores, "vISSQN"))}`, { size: 7, align: "right" });
rect(M + 4 * c5, y, c5, 8); cap(M + 4 * c5, y, "VALOR LÍQUIDO");
val(M + 4 * c5, y + 6, c5, `R$ ${moeda(txt(valores, "vLiq") || txt(dom, "vLiq"))}`, 8.5, true, "right"); y += 8;
doc.setFont("helvetica", "normal").setFontSize(5.5);
doc.text(`NFS-e nº ${txt(dom, "nNFSe")} · chave ${chave} · emitida em ${dataBR(txt(dom, "dhProc"))}.`, M, y + 4, { maxWidth: Wt });

const out = `${SCR}/danfse-${idx}.pdf`;
writeFileSync(out, Buffer.from(doc.output("arraybuffer")));
console.log("PDF salvo:", out);
process.exit(0);
